title: "Mattia Drago Board Games"
url: "https://www.mattiadragoboardgames.com"

theme: minima
minima:
  skin: auto

timezone: Europe/Rome
future: true
permalink: "/:categories/:title/"

# uso '>' per evitare problemi con i due punti nella descrizione
description: >
  Analisi di giochi da tavolo: origini & contesto, scelte di design, persone & storie, impatto sociale.

header_pages:
  - about.md
  - affiliazioni.md
  - contatti.md
  - index.md
